# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9001
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: roxygenize
        args: [--root=./app]
        additional_dependencies:
          - bslib
          - config
          - DT
          - fs
          - ggplot2
          - golem
          - shiny
          - DBI
          - duckdb
          - glue
          - tidyr
          - withr
          - forcats
          - readr
          - lubridate
          - dplyr
          - cli
          - nanoparquet
          - rlang
          - SAFEHR-data/omop-bundles
          - plotly
          - markdown
          - bsicons
          - CDMConnector
          - RPostgres
      # codemeta must be above use-tidy-description when both are used
      # -   id: codemeta-description-updated
      - id: use-tidy-description
        args: [--root=./app]
      # - id: lintr  # disabling lintr hook as it doesn't seem to correctly load the package
      # see also https://github.com/lorenzwalthert/precommit/issues/440
      - id: parsable-R
      - id: no-browser-statement
      - id: no-print-statement
      - id: no-debug-statement
      - id: deps-in-desc
        args: [--root=./app]
        exclude: "^scripts/|^app/dev/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: file-contents-sorter
        files: '^\.Rbuildignore$'
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files

ci:
  autoupdate_schedule: monthly
