services:
  omopcat:
    build:
      # Use repo root as context so we can copy scripts directory to container
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        OMOPCAT_DATA_PATH: /etc/omopcat/data
    image: omopcat:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      GOLEM_CONFIG_ACTIVE: production
      OMOPCAT_DATA_PATH: /etc/omopcat/data
      LOW_FREQUENCY_THRESHOLD: 5
      LOW_FREQUENCY_REPLACEMENT: 2.5
      # Enviornment variables required for the data pre-processing
      # these should be declared in a separate .env file
      DB_NAME: ${DB_NAME}
      HOST: ${HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CDM_SCHEMA: ${DB_CDM_SCHEMA}
    volumes:
      - ../data/prod_data:/etc/omopcat/data
    ports:
      - 3838:3838
