FROM nginx:1.29.3@sha256:ac27e318cff1c5340d9a2c2d8db5f0a374dabfe1f285f81348008e01bd980d4d

# Install certbot for SSL certificate creation and renewal
RUN apt update && \
    apt install -y python3 \
    python3-dev \
    python3-venv \
    libaugeas-dev \
    gcc \
    rustc \
    build-essential \
    libssl-dev \
    libffi-dev \
    cargo \
    pkg-config

RUN python3 -m venv /opt/certbot/ && \
    /opt/certbot/bin/pip install --upgrade pip && \
    /opt/certbot/bin/pip install certbot certbot-nginx && \
    ln -s /opt/certbot/bin/certbot /usr/bin/certbot



# Create certificates for SSL
COPY --chmod=755 www/create_certificates_and_run_nginx.sh /usr/local/bin/create_certificates_and_run_nginx.sh
 

CMD /usr/local/bin/create_certificates_and_run_nginx.sh