name: Build Docker Image

on:
  push:
    branches: ["main"]
    paths: ["deploy/**"]
  pull_request:
    branches: ["main"]
    paths: ["deploy/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag omopcat:$(date +%s)
        working-directory: deploy/
