name: Build Docker Image

on:
  push:
    branches: ["main"]
    paths: ["docker-compose.yml", "app/Dockerfile", "preprocessing/Dockerfile"]
  pull_request:
    branches: ["main"]
    paths: ["docker-compose.yml", "app/Dockerfile", "preprocessing/Dockerfile"]
  workflow_dispatch:

# Only run actions on the most recent push to a branch
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [omopcat, preprocess]

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cp .env.sample .env
          docker compose build ${{ matrix.image }}
