name: Build Docker Image

on:
  push:
    branches: ["main"]
    paths: ["deploy/**"]
  pull_request:
    branches: ["main"]
    paths: ["deploy/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Add dummy .Renviron file
        run: touch deploy/.Renviron
      - name: Build the Docker image
        run: docker compose build
        working-directory: deploy/
